### ISSUE TITLE
[FR] Please support dart language

### ISSUE THREAD

**Issue by monkeyWie** [liweiyi88/trendshift-backend#15]
![image](https://github.com/liweiyi88/trendshift-backend/assets/13160176/e5035e2c-a7a0-4246-ae5b-0aa96cc88be1)

Dart language is becoming more and more popular, please support it as well, thanks for your awesome project!

**Comment by liweiyi88** [comment]
Hi @monkeyWie thanks for reaching out.
The changes have been deployed and Dart is supported from today.
Just in case you are not aware, you could also collect the dynamic badge for yourself and your repositories.
For example, https://trendshift.io/repositories/7953 and https://trendshift.io/developers/792. 😄

**Comment by monkeyWie** [comment]
> Hi @monkeyWie thanks for reaching out. The changes have been deployed and Dart is supported from today. Just in case you are not aware, you could also collect the dynamic badge for yourself and your repositories. For example, https://trendshift.io/repositories/7953 and https://trendshift.io/developers/792. 😄

Wow, thanks, that's exactly what I'm gonna do.

**Comment by monkeyWie** [comment]
Unfortunately, the historical data is all gone, right?
